# Build

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: R ${{ matrix.config.r }} | ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'devel'}
    
    env:
        GEONODE_USER: ${{ secrets.GEONODE_USER }}
        GEONODE_PASSWORD: ${{ secrets.GEONODE_PASSWORD }}
    
    steps:
      - uses: actions/checkout@v2
      #R Set-up
      - name: Set up R ${{ matrix.config.r }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      #Install dependencies
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::XML
          needs: check
          cache-version: 5
          
      #Check R Package
      - name: Check R package
        uses: r-lib/actions/check-r-package@v2
        with:
          artifact-name: geonode4R_r-${{ matrix.config.r }}_${{ matrix.config.os }}-results
